// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TcUnit_VsExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTcUnitPackageString = "cfe9289a-39cb-4a97-be31-61d2e9763163";
        public const string TwincatPlcProjectCmdSetString = "3b11520b-7e70-4008-a6cf-b60ae84e12b1";
        public const string guidTcUnitPackageCmdSetString = "eb15d4da-46d4-42b2-8130-4971b2ef53af";
        public const string guidImagesString = "e5c270b5-e48c-47c0-8890-2a6f2d454eef";
        public static Guid guidTcUnitPackage = new Guid(guidTcUnitPackageString);
        public static Guid TwincatPlcProjectCmdSet = new Guid(TwincatPlcProjectCmdSetString);
        public static Guid guidTcUnitPackageCmdSet = new Guid(guidTcUnitPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TwinCatProjectContextMenuId = 0x9013;
        public const int TwincatFileContextMenuId = 0x9011;
        public const int TwinCatFolderContextMenuId = 0x9010;
        public const int TwinCatPLCCodeEditorContextMenuId = 0x9017;
        public const int AddUnitTestSuiteCommandId = 0x0100;
        public const int AddUnitTestCaseCommandId = 0x0200;
        public const int TwinCatContextMenuGroup = 0x1250;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
    }
}
